In [1]:
import pandas as pd
import numpy as np

# Read in county-level results
* Number of votes
* North Dakota is for the whole state

In [2]:
alabama = 'data/alabama_results.xlsx'
arkansas = 'data/arkansas_results.xlsx'
california = 'data/california_results.xlsx'
colorado = 'data/colorado_results.xlsx'
idaho = 'data/idaho_results.xlsx'
iowa = 'data/iowa_results.xlsx'
maine = 'data/maine_results.xlsx'
massachusetts = 'data/massachusetts_results.xlsx'
michigan = 'data/michigan_results.xlsx'
minnesota = 'data/minnesota_results.xlsx'
mississippi = 'data/mississippi_results.xlsx'
missouri = 'data/missouri_results.xlsx'
nevada = 'data/nevada_results.xlsx'
new_hampshire = 'data/new_hampshire_results.xlsx'
north_carolina = 'data/north-carolina_results.xlsx'
north_dakota = 'data/north-dakota_results.xlsx'
oklahoma = 'data/oklahoma_results.xlsx'
south_carolina = 'data/south_carolina_results.xlsx'
tennessee = 'data/tennessee_results.xlsx'
texas = 'data/texas_results.xlsx'
utah = 'data/utah_results.xlsx'
vermont = 'data/vermont_results.xlsx'
virginia = 'data/virginia_results.xlsx'
washington = 'data/washington_results.xlsx'

In [3]:
# create list  containing states and state abbreviations
state_list = [[alabama, 'AL'],
              [arkansas, 'AR'],
              [california, 'CA'],
              [colorado, 'CO'],
              [idaho, 'ID'],
              [iowa, 'IA'],
              [maine, 'ME'],
              [massachusetts, 'MA'],
              [michigan, 'MI'],
              [minnesota, 'MN'],
              [mississippi, 'MS'],
              [missouri, 'MO'],
              [nevada, 'NV'],
              [new_hampshire, 'NH'],
              [north_carolina, 'NC'],
              [north_dakota, 'ND'],
              [oklahoma, 'OK'],
              [south_carolina, 'SC'],
              [tennessee, 'TN'],
              [texas, 'TX'],
              [utah, 'UT'],
              [vermont, 'VT'],
              [virginia, 'VA'],
              [washington, 'WA']]

In [5]:
oklahoma

'data/oklahoma_results.xlsx'

# Combine Election Results
* Results are combined into one dataframe with the state abbreviation added on

In [4]:
# function for combining all the state results
def combine_results(state_list):
    
    global all_results
    
    all_results = pd.DataFrame()
    
    for state in state_list:
        results = pd.read_excel(state[0])
        active_candidates = ['Bernie Sanders', 'Joe Biden']
        active_candidates_LN = ['Sanders', 'Biden']
        
        results_df = results.transpose().reset_index()
        results_df.columns = results_df.iloc[0]
        results_df = results_df.drop(results_df.index[0])
        results_df = results_df.melt(id_vars=['Counties'],value_vars=results_df.columns.to_list()[1:-1])
        results_df['State'] = state[1]
        results_df = results_df[results_df['Counties'].isin(active_candidates_LN)]
        results_df = results_df.sort_values(by=[0, 'value'], ascending=False)

        results_df.rename(columns={"Counties": "last name", 0: "county", "State": "state", 'value': 'votes'}, inplace=True)
        
        all_results = all_results.append(results_df)

combine_results(state_list)

In [5]:
all_results

    last name      county votes state
976     Biden      Wilcox  1864    AL
975   Sanders      Wilcox   284    AL
961     Biden  Washington  1109    AL
960   Sanders  Washington   156    AL
946     Biden      Walker  1390    AL
..        ...         ...   ...   ...
26    Sanders      Benton  6911    WA
14      Biden      Asotin  1118    WA
13    Sanders      Asotin   705    WA
0     Sanders       Adams   288    WA
1       Biden       Adams   284    WA

[3200 rows x 4 columns]

# Import county facts
* A few of the columns are renamed

In [119]:
county_facts = pd.read_csv('data/county_facts.csv')
county_facts = county_facts.rename(columns={'state_abbreviation': 'state', 'area_name': 'county'})

# Add a merge column
* Add a merging column to both dataframes
* This column standardizes the county name to make merging easier

In [123]:
all_results['county_merge'] = ''

for index,row in all_results.iterrows():
    
    split_county = []
    county_name = ''
    
    split_county = row['county'].lower().split()

    if 'county' in split_county:
        split_county.remove('county')
    
    county_name = ''.join(split_county)

    row['county_merge'] = county_name

In [124]:
county_facts['county_merge'] = ''

for index,row in county_facts.iterrows():
    
    split_county = []
    county_name = ''
    
    split_county = row['county'].lower().split()

    if 'county' in split_county:
        split_county.remove('county')
    
    county_name = ''.join(split_county)

    county_facts.loc[index, 'county_merge'] = county_name

In [132]:
merged = pd.merge(all_results, county_facts, how='inner', on=['county_merge', 'state'])

# TODO drop county_y and rename county_X

In [133]:
merged

,last name,county_x,votes,state,county_merge,fips,county_y,PST045214,PST040210,PST120214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
0,Biden,Wilcox,1864,AL,wilcox,1131,Wilcox County,11098,11665,-4.9,...,0.0,37.6,0,21337,75708,6018,12949,0,888.50,13.1
1,Sanders,Wilcox,284,AL,wilcox,1131,Wilcox County,11098,11665,-4.9,...,0.0,37.6,0,21337,75708,6018,12949,0,888.50,13.1
2,Biden,Washington,1109,AL,washington,1129,Washington County,16834,17583,-4.3,...,0.0,25.6,1153449,32856,76343,4458,0,2,1080.21,16.3
3,Sanders,Washington,156,AL,washington,1129,Washington County,16834,17583,-4.3,...,0.0,25.6,1153449,32856,76343,4458,0,2,1080.21,16.3
4,Biden,Walker,1390,AL,walker,1127,Walker County,65471,67023,-2.3,...,0.0,23.8,314804,256377,903643,13162,73895,8,791.19,84.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3183,Sanders,Benton,6911,WA,benton,53005,Benton County,186486,175177,6.5,...,5.4,29.6,0,755416,2122018,13309,238019,942,1700.38,103.0
3184,Biden,Asotin,1118,WA,asotin,53003,Asotin County,22189,21623,2.6,...,0.0,17.0,0,0,208856,9867,22983,35,636.21,34.0
3185,Sanders,Asotin,705,WA,asotin,53003,Asotin County,22189,21623,2.6,...,0.0,17.0,0,0,208856,9867,22983,35,636.21,34.0
3186,Sanders,Adams,288,WA,adams,53001,Adams County,19179,18728,2.4,...,16.3,0.0,442178,574216,144809,8547,14844,50,1924.98,9.7
3187,Biden,Adams,284,WA,adams,53001,Adams County,19179,18728,2.4,...,16.3,0.0,442178,574216,144809,8547,14844,50,1924.98,9.7

### Merging looks good except for the O Brien county
* These are the NAN rows from a left join
* TODO: rename O Brien county in the county facts sheet

In [131]:
merged[merged.isna().any(axis=1)]

,last name,county_x,votes,state,county_merge,fips,county_y,PST045214,PST040210,PST120214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
640,Biden,Satellite caucus 5,71,IA,satellitecaucus5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
641,Sanders,Satellite caucus 5,56,IA,satellitecaucus5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
642,Sanders,Satellite caucus 4,301,IA,satellitecaucus4,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
643,Biden,Satellite caucus 4,21,IA,satellitecaucus4,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
644,Sanders,Satellite caucus 3,1245,IA,satellitecaucus3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
645,Biden,Satellite caucus 3,298,IA,satellitecaucus3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
646,Sanders,Satellite caucus 2,583,IA,satellitecaucus2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
647,Biden,Satellite caucus 2,68,IA,satellitecaucus2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
648,Sanders,Satellite caucus 1,365,IA,satellitecaucus1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
649,Biden,Satellite caucus 1,67,IA,satellitecaucus1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
670,Biden,O Brien,87,IA,obrien,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
671,Sanders,O Brien,65,IA,obrien,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Merge candidate features
* Import the candidate features and merge into the dataframe on the last name

In [101]:
candidate_features = pd.read_excel('data/candidate_features.xlsx')
candidate_features = candidate_features.head(2)
candidate_features.rename(columns={"Candidate": "last name"}, inplace=True)

In [102]:
candidate_features

,last name,Age,Gender,Net Worth,% Donations Under $200,Candidate Committee Money,Outside Money,Twitter Followers,legalize_cannabis,vote_incarcerated,...,carbon_tax,north_korea_meet,free_college,children_public,ban_fracking,border_crossing_penalties,medicare_for_all,private_insurance,eliminate_electoral_college,eliminate_filibuster
0,Sanders,78,Male,2000000.0,0.5576,132564706.0,1505287.0,10.8,1.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
1,Biden,77,Male,9000000.0,0.3624,68281497.0,7919417.0,4.2,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [109]:
merged = pd.merge(merged, candidate_features, how='inner', on='last name')

In [110]:
merged

,last name,county_x,votes,state,county_merge,fips,county_y,PST045214,PST040210,PST120214,...,carbon_tax,north_korea_meet,free_college,children_public,ban_fracking,border_crossing_penalties,medicare_for_all,private_insurance,eliminate_electoral_college,eliminate_filibuster
0,Biden,Wilcox,1864,AL,wilcox,1131,Wilcox County,11098,11665,-4.9,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,Biden,Washington,1109,AL,washington,1129,Washington County,16834,17583,-4.3,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,Biden,Walker,1390,AL,walker,1127,Walker County,65471,67023,-2.3,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,Biden,Tuscaloosa,11825,AL,tuscaloosa,1125,Tuscaloosa County,202212,194653,3.9,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,Biden,Tallapoosa,1762,AL,tallapoosa,1123,Tallapoosa County,41165,41618,-1.1,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3183,Sanders,Clallam,5486,WA,clallam,53009,Clallam County,72715,71404,1.8,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
3184,Sanders,Chelan,4075,WA,chelan,53007,Chelan County,74588,72456,2.9,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
3185,Sanders,Benton,6911,WA,benton,53005,Benton County,186486,175177,6.5,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
3186,Sanders,Asotin,705,WA,asotin,53003,Asotin County,22189,21623,2.6,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
3187,Sanders,Adams,288,WA,adams,53001,Adams County,19179,18728,2.4,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0